/**
 * Единый каталог предметов — сгенерировано tools/generate-items-catalog.js
 * Не редактировать вручную. Источник: tools/items-migrated.json
 * Сборка: bash tools/build-catalog.sh
 */

const ITEM_CATALOG_RAW = {
  antitoxin: {
    id: "antitoxin",
    name: "Антидот",
    icon: "🧴",
    color: "#79c0ff",
    shape: [[0,0]],
    rarity: "uncommon",
    cost: 3,
    tags: ["utility","nature","heal"],
    cooldown: 3.5,
    staminaCost: 0,
    effects: [
      { type: "heal", value: 4 }
    ],
  },
  apple: {
    id: "apple",
    name: "Яблоко",
    icon: "🍎",
    color: "#f85149",
    shape: [[0,0]],
    rarity: "common",
    cost: 1,
    tags: ["food","heal"],
    cooldown: 2.5,
    staminaCost: 0,
    effects: [
      { type: "heal", value: 3 }
    ],
  },
  apprentice_staff: {
    id: "apprentice_staff",
    name: "Посох ученика",
    icon: "🪄",
    color: "#a371f7",
    shape: [[0,0],[0,1]],
    rarity: "common",
    cost: 3,
    tags: ["weapon","magic","melee"],
    damage: 2,
    cooldown: 2.5,
    staminaCost: 12,
    effects: [
      { type: "damage", value: 2, valueMin: 1, valueMax: 3, damageType: "magic" }
    ],
  },
  backpack: {
    id: "backpack",
    name: "Рюкзак",
    icon: "🎒",
    color: "#4a6741",
    shape: [[0,0],[0,1],[0,2]],
    internalCols: 1,
    internalRows: 3,
    isContainer: true,
    shopContainer: true,
    immovable: false,
    rarity: "uncommon",
    cost: 4,
    tags: ["bag"],
    stats: {},
    cooldown: 0,
    effects: [],
    synergies: [],
    _isContainerEntry: true,
  },
  bag_of_stones: {
    id: "bag_of_stones",
    name: "Мешок камней",
    icon: "🪨",
    color: "#58a6ff",
    shape: [[0,0]],
    rarity: "rare",
    cost: 3,
    tags: ["accessory","nature"],
    cooldown: 0,
    effects: [
      { type: "stonesMultiThrow", trigger: "passive" }
    ],
    description: "Камни можно метать многократно.",
    buildHints: "Универсальный / автономный",
  },
  banana: {
    id: "banana",
    name: "Банан",
    icon: "🍌",
    color: "#8b949e",
    shape: [[0,0]],
    rarity: "common",
    cost: 3,
    tags: ["food","nature"],
    cooldown: 5,
    effects: [
      { type: "periodic", interval: 5, trigger: "passive", heal: 4, restoreStamina: 1 }
    ],
    description: "Каждые 5с: +4 HP и +1 выносливости.",
    buildHints: "Билд: еда / Pan · Синергия: стан → Dagger extra attack",
  },
  bandage: {
    id: "bandage",
    name: "Бинт",
    icon: "🩹",
    color: "#56d364",
    shape: [[0,0]],
    rarity: "common",
    cost: 1,
    tags: ["utility","food","heal"],
    cooldown: 3,
    staminaCost: 0,
    effects: [
      { type: "heal", value: 3 }
    ],
  },
  blueberries: {
    id: "blueberries",
    name: "Черника",
    icon: "🫐",
    color: "#58a6ff",
    shape: [[0,0]],
    rarity: "rare",
    cost: 2,
    tags: ["food","magic"],
    cooldown: 3.5,
    effects: [
      { type: "heal", value: 2 },
      { type: "periodic", interval: 3.5, trigger: "passive", gainWeakestStack: {"minStack":10,"altStack":"mana","value":1} }
    ],
    description: "Каждые 3.5с: +1 к самому слабому стаку (×2 маны при 10+ маны).",
    buildHints: "Билд: мана / магия, еда / Pan · Пары: Mana Orb, Mana Potion, магические посохи",
  },
  broom: {
    id: "broom",
    name: "Метла",
    icon: "🧹",
    color: "#8b949e",
    shape: [[0,0],[0,1]],
    rarity: "common",
    cost: 4,
    tags: ["weapon","debuff","melee"],
    damage: 3,
    cooldown: 1.7,
    staminaCost: 1.5,
    effects: [
      { type: "damage", value: 3, valueMin: 2, valueMax: 4 },
      { type: "attackBuff", value: 2, trigger: "on_miss" },
      { type: "poison", value: 1, chance: 0.33, trigger: "on_hit" }
    ],
    description: "При промахе: +2 урона след. атаке. При попадании: 33% +1 яд.",
    buildHints: "Пары: Whetstone, Gloves of Haste",
    sockets: 1,
  },
  cap_of_resilience: {
    id: "cap_of_resilience",
    name: "Шапка стойкости",
    icon: "🧢💪",
    color: "#a371f7",
    shape: [[0,0],[0,1]],
    rarity: "epic",
    cost: 7,
    tags: ["armor","helmet","craft"],
    cooldown: 0,
    effects: [
      { type: "statMult", stat: "damage", value: 0.08, trigger: "passive" },
      { type: "timedDamageReduction", value: 0.25, duration: 3, trigger: "battle_start" }
    ],
    description: "В начале боя: Снизить получаемый урон на 25% на 3с. 15% шанс сопротивляться критические удары блока 15% шанс сопротивляться оглушениям блока",
    buildHints: "Универсальный / автономный",
    sockets: 1,
  },
  charge_gem: {
    id: "charge_gem",
    name: "Камень зарядов",
    icon: "⚡",
    color: "#a371f7",
    shape: [[0,0]],
    rarity: "uncommon",
    cost: 3,
    tags: ["magic","gem"],
    cooldown: 2,
    staminaCost: 0,
    effects: [
      { type: "gainStack", stack: "mana", value: 1 }
    ],
    description: "[при активации]: +1 мана.",
  },
  cheese: {
    id: "cheese",
    name: "Сыр",
    icon: "🧀",
    color: "#f0c14b",
    shape: [[0,0]],
    rarity: "legendary",
    cost: 8,
    tags: ["food","pet"],
    cooldown: 3.8,
    effects: [
      { type: "heal", value: 3 },
      { type: "periodic", interval: 3.8, trigger: "passive", maxHp: 10, randomTimedBuff: true }
    ],
    description: "Каждые 3.8с: +10 макс. HP и случайный бафф.",
    buildHints: "Билд: питомцы, еда / Pan",
  },
  chipped_amethyst: {
    id: "chipped_amethyst",
    name: "Сколотый аметист",
    icon: "◇💜",
    color: "#8b949e",
    shape: [[0,0]],
    rarity: "common",
    cost: 1,
    tags: ["gem","magic","craft"],
    cooldown: 0,
    effects: [
      { type: "statMult", stat: "magicDamage", value: 0.1, trigger: "passive" }
    ],
    description: "Сколотый аметист: Сокет оружия: Шанс снять баффы на попадание. Сокет аксессуара: +маны. Сокет брони: +магия сопротивление.",
    buildHints: "Ветка Amethyst · Мана-билды",
  },
  chipped_emerald: {
    id: "chipped_emerald",
    name: "Сколотый изумруд",
    icon: "◇💚",
    color: "#8b949e",
    shape: [[0,0]],
    rarity: "common",
    cost: 1,
    tags: ["gem","nature","craft"],
    cooldown: 3,
    effects: [
      { type: "heal", value: 3 },
      { type: "passiveMaxHp", value: 5, trigger: "passive" }
    ],
    description: "Сколотый изумруд: Сокет оружия: Лечение на попадание. Сокет аксессуара: +макс. ОЗ. Сокет брони: +реген.",
    buildHints: "Ветка Emerald · Анти-яд в броню",
  },
  chipped_ruby: {
    id: "chipped_ruby",
    name: "Сколотый рубин",
    icon: "◇❤️",
    color: "#8b949e",
    shape: [[0,0]],
    rarity: "common",
    cost: 1,
    tags: ["gem","fire","craft"],
    cooldown: 0,
    effects: [
      { type: "groundFire", value: 2 },
      { type: "statMult", stat: "damage", value: 0.06, trigger: "passive" }
    ],
    description: "Сколотый рубин: Сокет оружия: Шанс получить Жар на попадание. Сокет аксессуара: +урон. Сокет брони: Сопротивление Холоду.",
    buildHints: "Ветка Ruby: → Flawed → … → Perfect · Вставка в оружие",
  },
  chipped_sapphire: {
    id: "chipped_sapphire",
    name: "Сколотый сапфир",
    icon: "◇💙",
    color: "#8b949e",
    shape: [[0,0]],
    rarity: "common",
    cost: 1,
    tags: ["gem","cold","craft"],
    cooldown: 3,
    effects: [
      { type: "slow", value: 0.1, duration: 3 },
      { type: "statMult", stat: "cooldown", value: -0.05, trigger: "passive" }
    ],
    description: "Сколотый сапфир: Сокет оружия: Шанс наложить Холод на попадание. Сокет аксессуара: +удача. Сокет брони: +блок.",
    buildHints: "Ветка Sapphire · Ледяные крафты",
  },
  chipped_topaz: {
    id: "chipped_topaz",
    name: "Сколотый топаз",
    icon: "◇💛",
    color: "#8b949e",
    shape: [[0,0]],
    rarity: "common",
    cost: 1,
    tags: ["gem","luck","craft"],
    cooldown: 0,
    effects: [
      { type: "statMult", stat: "cooldown", value: -0.08, trigger: "passive" }
    ],
    description: "Сколотый топаз: Сокет оружия: Быстрее атаки. Сокет аксессуара: Предметы срабатывает быстрее. Сокет брони: +выносливости реген.",
    buildHints: "Ветка Topaz · Ranger / крит",
  },
  cork_charm: {
    id: "cork_charm",
    name: "Пробка-оберег",
    icon: "🧿",
    color: "#6e7681",
    shape: [[0,0]],
    rarity: "common",
    cost: 2,
    tags: ["utility","accessory"],
    cooldown: 5,
    staminaCost: 0,
    effects: [
      { type: "block", value: 2 }
    ],
  },
  customer_card: {
    id: "customer_card",
    name: "Карта покупателя",
    icon: "💳",
    color: "#58a6ff",
    shape: [[0,0]],
    rarity: "rare",
    cost: 4,
    tags: ["accessory","treasure"],
    cooldown: 0,
    effects: [
      { type: "procChanceBonus", value: 0.1, trigger: "passive" }
    ],
    metaEffects: [
      { phase: "shop_refresh", type: "rarity_up", value: 1 },
      { phase: "shop_refresh", type: "trade_offer", chance: 0.1, value: 3 }
    ],
    description: "Магазин: повышение редкости. +10% к прокам.",
    buildHints: "Билд: экономика / золото",
  },
  dagger: {
    id: "dagger",
    name: "Кинжал",
    icon: "🔪",
    color: "#c9d1d9",
    shape: [[0,0]],
    rarity: "common",
    cost: 2,
    tags: ["weapon","melee"],
    damage: 2,
    cooldown: 1.5,
    staminaCost: 8,
    effects: [
      { type: "damage", value: 2, valueMin: 1, valueMax: 3 },
      { type: "extraAttackOnStun", trigger: "passive" }
    ],
  },
  deck_of_cards: {
    id: "deck_of_cards",
    name: "Колода карт",
    icon: "🃏",
    color: "#58a6ff",
    shape: [[0,0]],
    rarity: "rare",
    cost: 3,
    tags: ["accessory","card","luck"],
    cooldown: 0,
    effects: [
      { type: "statMult", stat: "damage", value: 0.08, trigger: "passive" },
      { type: "gainStack", stack: "luck", value: 2, trigger: "battle_start" },
      { type: "procChanceBonus", value: 0.05, trigger: "passive" }
    ],
    metaEffects: [
      { phase: "shop_pool", type: "offer_tag", tag: "card" }
    ],
    description: "В начале боя: +2 удачи. +5% к прокам.",
    buildHints: "RNG / карточные эффекты · Ветка: Ace of Spades, The Fool, драконы",
  },
  divine_potion: {
    id: "divine_potion",
    name: "Божественное зелье",
    icon: "🧪✨",
    color: "#ff7b72",
    shape: [[0,0]],
    rarity: "godly",
    cost: 7,
    tags: ["potion","consumable","holy"],
    cooldown: 3,
    effects: [
      { type: "heal", value: 12 },
      { type: "debuffThreshold", threshold: 10, once: true, trigger: "passive", cleanseDebuffs: 10 }
    ],
    description: "При 10+ дебаффах: снять 10.",
    buildHints: "Универсальный / автономный",
  },
  fanny_pack: {
    id: "fanny_pack",
    name: "Поясная сумка",
    icon: "🎒",
    color: "#58a6ff",
    shape: [[0,0],[0,1]],
    internalCols: 1,
    internalRows: 2,
    isContainer: true,
    shopContainer: true,
    immovable: false,
    rarity: "rare",
    cost: 3,
    tags: ["bag"],
    stats: {},
    cooldown: 0,
    effects: [],
    synergies: [],
    description: "Предметы внутри на 10% быстрее.",
    buildHints: "Универсальный / автономный",
    _isContainerEntry: true,
  },
  fire_crystal: {
    id: "fire_crystal",
    name: "Огненный кристалл",
    icon: "🔥",
    color: "#f0883e",
    shape: [[0,0],[0,1]],
    rarity: "uncommon",
    cost: 6,
    tags: ["fire","gem"],
    cooldown: 2.5,
    staminaCost: 0,
    effects: [
      { type: "damage", value: 5, damageType: "fire", valueMin: 2, valueMax: 5 }
    ],
  },
  fire_staff: {
    id: "fire_staff",
    name: "Огненный посох",
    icon: "🔥",
    color: "#f0883e",
    shape: [[0,0],[0,1],[1,1]],
    classRestriction: "mage",
    rarity: "legendary",
    cost: 12,
    tags: ["weapon","magic","fire","melee"],
    damage: 11,
    cooldown: 3,
    staminaCost: 15,
    effects: [
      { type: "damage", value: 11, damageType: "fire", valueMin: 6, valueMax: 11 },
      { type: "groundFire", value: 3, trigger: "passive" },
      { type: "shieldBreakBonus", value: 0.15, trigger: "passive" }
    ],
    synergies: [
      { id: "fire_gem_boost", adjacency: "weak", neighborTags: ["gem"], target: "self", apply: { type: "damageBonus", value: 2 }, desc: "+2 урона рядом с кристаллом (диаг.)" }
    ],
  },
  fly_agaric: {
    id: "fly_agaric",
    name: "Мухомор",
    icon: "🍄",
    color: "#58a6ff",
    shape: [[0,0]],
    rarity: "rare",
    cost: 3,
    tags: ["food","poison","nature"],
    cooldown: 4,
    effects: [
      { type: "buffTimed", stat: "damage", value: 0.15, duration: 5 },
      { type: "periodic", interval: 3.6, trigger: "passive", foePoison: 1 }
    ],
    description: "Каждые 3.6с: +1 яд.",
    buildHints: "Билд: яд / DoT, еда / Pan · Пары: Pestilence Flask, Death Scythe, ядовитые питомцы",
  },
  frost_crystal: {
    id: "frost_crystal",
    name: "Морозный кристалл",
    icon: "❄️",
    color: "#79c0ff",
    shape: [[0,0],[0,1]],
    rarity: "uncommon",
    cost: 6,
    tags: ["magic","gem","cold"],
    damage: 4,
    cooldown: 3,
    staminaCost: 0,
    effects: [
      { type: "damage", value: 4, damageType: "magic", valueMin: 1, valueMax: 4 },
      { type: "slow", value: 0.15, duration: 3 }
    ],
  },
  garlic: {
    id: "garlic",
    name: "Чеснок",
    icon: "🧄",
    color: "#8b949e",
    shape: [[0,0]],
    rarity: "common",
    cost: 2,
    tags: ["food","poison","nature"],
    cooldown: 4,
    effects: [
      { type: "heal", value: 2 },
      { type: "periodic", interval: 4, trigger: "passive", gainStack: {"stack":"block","value":3}, cleanseDebuffs: 1, cleanseChance: 0.3 }
    ],
    description: "Каждые 4с: +3 блока. 30% снять 1 дебафф.",
    buildHints: "Билд: яд / DoT, еда / Pan · Пары: Pestilence Flask, Death Scythe, ядовитые питомцы",
  },
  glowing_crown: {
    id: "glowing_crown",
    name: "Сияющая корона",
    icon: "👑✨",
    color: "#ff7b72",
    shape: [[0,0],[0,1]],
    rarity: "godly",
    cost: 12,
    tags: ["armor","helmet","holy"],
    cooldown: 2.4,
    effects: [
      { type: "periodic", interval: 2.4, trigger: "passive", cleanseDebuffs: 1, heal: 5 },
      { type: "invulnOnStaminaSpend", staminaCost: 10, duration: 2, trigger: "passive" }
    ],
    synergies: [
      { id: "glowing_crown_aura", adjacency: "strong", neighborTags: ["weapon","pet","armor","shield"], target: "neighbor", apply: { type: "damageBonus", value: 1 }, desc: "Аура силы соседним предметам" }
    ],
    description: "Каждые 2.4с: снять 1 дебафф и +5 HP. Потратить 10 выносливости: неуязвимость 2с.",
    buildHints: "Универсальный / автономный",
    sockets: 1,
  },
  hammer: {
    id: "hammer",
    name: "Молот",
    icon: "🔨",
    color: "#58a6ff",
    shape: [[0,0],[0,1]],
    rarity: "rare",
    cost: 8,
    tags: ["weapon","melee","stun"],
    damage: 11,
    cooldown: 2,
    staminaCost: 3,
    effects: [
      { type: "damage", value: 11, valueMin: 10, valueMax: 13 },
      { type: "slow", value: 0.18, duration: 2 },
      { type: "applyStun", chance: 0.45, duration: 0.5, trigger: "on_hit" }
    ],
    description: "При попадании: 45% шанс оглушить на 0.5с.",
    buildHints: "Билд: стан · Пары: Dagger (extra attack) · Утилита: Piggybank → монеты",
    sockets: 2,
  },
  healing_herb: {
    id: "healing_herb",
    name: "Целебная трава",
    icon: "🌿",
    color: "#56d364",
    shape: [[0,0],[1,0]],
    rarity: "common",
    cost: 2,
    tags: ["food","nature","heal"],
    cooldown: 4,
    staminaCost: 0,
    effects: [
      { type: "heal", value: 5 }
    ],
    synergies: [
      { id: "nature_food_boost", adjacency: "strong", neighborTags: ["nature"], target: "self", apply: { type: "healBonus", value: 1 }, desc: "+1 лечения рядом с природой" }
    ],
  },
  healing_herbs: {
    id: "healing_herbs",
    name: "Целебные травы",
    icon: "🌿",
    color: "#8b949e",
    shape: [[0,0]],
    rarity: "common",
    cost: 4,
    tags: ["food","nature"],
    cooldown: 4,
    effects: [
      { type: "statMult", stat: "damage", value: 0.08, trigger: "passive" },
      { type: "gainStack", stack: "luck", value: 2, trigger: "battle_start" }
    ],
    description: "В начале боя: +2 удачи.",
    buildHints: "Билд: еда / Pan",
  },
  health_potion: {
    id: "health_potion",
    name: "Зелье здоровья",
    icon: "🧪❤️",
    color: "#58a6ff",
    shape: [[0,0]],
    rarity: "rare",
    cost: 4,
    tags: ["potion","consumable","heal","nature"],
    cooldown: 3,
    effects: [
      { type: "heal", value: 6 },
      { type: "hpThreshold", threshold: 0.5, direction: "below", once: true, trigger: "passive", heal: 11, cleanseDebuffs: 4 }
    ],
    description: "При HP ниже 50%: +11 HP и снять 4 дебаффа (раз).",
    buildHints: "Универсальный сейв · Ветка: Strong Health, Mana Potion · Пары: Potion Belt",
  },
  health_stone: {
    id: "health_stone",
    name: "Камень здоровья",
    icon: "❤️",
    color: "#f85149",
    shape: [[0,0]],
    rarity: "uncommon",
    cost: 5,
    tags: ["gem","heal"],
    maxHp: 12,
    cooldown: 5,
    staminaCost: 0,
    effects: [
      { type: "passiveMaxHp", value: 12, trigger: "passive" },
      { type: "heal", value: 4 }
    ],
    synergies: [
      { id: "health_stone_food", adjacency: "strong", neighborTags: ["food"], target: "self", apply: { type: "healBonus", value: 1 }, desc: "Рядом с едой: +1 к лечению" }
    ],
  },
  heroic_potion: {
    id: "heroic_potion",
    name: "Геройское зелье",
    icon: "🧪⚔️",
    color: "#f0c14b",
    shape: [[0,0]],
    rarity: "legendary",
    cost: 6,
    tags: ["potion","consumable","stamina"],
    cooldown: 3,
    effects: [
      { type: "buffTimed", stat: "damage", value: 0.2, duration: 5 },
      { type: "zeroStamina", restoreStamina: 2, gainStack: {"stack":"empower","value":1}, trigger: "passive" }
    ],
    description: "При нулевой выносливости: +2 выносливости и +1 усиление.",
    buildHints: "Билд: оружие со стаминой · Крафт: Eggscalibur · Пары: Stamina Sack, много ⚡-оружия",
  },
  holy_armor: {
    id: "holy_armor",
    name: "Святая броня",
    icon: "🦺✨",
    color: "#f0c14b",
    shape: shapeRect(2, 3),
    rarity: "legendary",
    cost: 12,
    tags: ["armor","holy"],
    defense: 4,
    cooldown: 2.2,
    effects: [
      { type: "passiveDefense", value: 4, trigger: "passive" },
      { type: "gainStack", stack: "block", value: 65, trigger: "battle_start" },
      { type: "tagScaledStack", stack: "block", perTag: 2, tag: "armor", trigger: "battle_start" },
      { type: "periodic", interval: 2.2, trigger: "passive", spendStack: {"stack":"block","value":2,"cleansePoisonSelf":1} }
    ],
    description: "В начале боя: +65 блока и +2 блока за каждый предмет брони. Каждые 2.2с: потратить 2 блока (очистка).",
    buildHints: "Билд: анти-яд / святой · Пары: Holy Spear, святые аксессуары",
    sockets: 3,
  },
  hungry_blade: {
    id: "hungry_blade",
    name: "Голодный клинок",
    icon: "🗡️🩸",
    color: "#a371f7",
    shape: [[0,0],[0,1]],
    rarity: "epic",
    cost: 7,
    tags: ["weapon","melee","vampiric","craft"],
    damage: 4,
    cooldown: 1.6,
    staminaCost: 1,
    effects: [
      { type: "statMult", stat: "damage", value: 0.08, trigger: "passive" },
      { type: "damage", value: 4, valueMin: 3, valueMax: 6 },
      { type: "gainStack", stack: "spikes", value: 1, trigger: "battle_start" },
      { type: "gainStack", stack: "spikes", value: 1, trigger: "on_hit" },
      { type: "damagePerStack", stack: "spikes", value: 1, trigger: "passive" }
    ],
    description: "В начале боя: +1 шип. При попадании: +1 шип. +1 урона за шип.",
    buildHints: "Билд: вампиризм · Ветка: Manathirst / Bloodthorne / Frostbite · Пары: Healing Herbs, реген",
    sockets: 1,
  },
  iron_helmet: {
    id: "iron_helmet",
    name: "Железный шлем",
    icon: "⛑️",
    color: "#6e7681",
    shape: [[0,0],[0,1]],
    rarity: "common",
    cost: 2,
    tags: ["armor","helmet"],
    defense: 3,
    cooldown: 4,
    staminaCost: 0,
    effects: [
      { type: "passiveDefense", value: 3, trigger: "passive" },
      { type: "block", value: 4 }
    ],
  },
  iron_patch: {
    id: "iron_patch",
    name: "Железная заплатка",
    icon: "🔩",
    color: "#6e7681",
    shape: [[0,0],[0,1]],
    rarity: "common",
    cost: 3,
    tags: ["utility"],
    cooldown: 0,
    staminaCost: 0,
    effects: [
      { type: "passiveDefense", value: 2, trigger: "passive" }
    ],
  },
  iron_shield: {
    id: "iron_shield",
    name: "Железный щит",
    icon: "🛡️",
    color: "#6e7681",
    shape: [[0,0],[1,0]],
    rarity: "common",
    cost: 3,
    tags: ["armor","shield"],
    cooldown: 3,
    staminaCost: 0,
    effects: [
      { type: "block", value: 5 }
    ],
    synergies: [
      { id: "shield_weapon_buff", adjacency: "strong", neighborTags: ["weapon"], target: "self", apply: { type: "grantBlockBuff", value: 3, buffTargetTags: ["weapon"], cap: 12 }, desc: "[при блоке]: +3 к атаке соседнего оружия" }
    ],
  },
  knight_sword: {
    id: "knight_sword",
    name: "Меч рыцаря",
    icon: "⚔️",
    color: "#79c0ff",
    shape: [[0,0],[0,1],[0,2]],
    rarity: "rare",
    cost: 9,
    tags: ["weapon","melee"],
    damage: 16,
    cooldown: 3.2,
    staminaCost: 17,
    effects: [
      { type: "damage", value: 16, valueMin: 12, valueMax: 16 }
    ],
  },
  leather_armor: {
    id: "leather_armor",
    name: "Кожаная броня",
    icon: "🦺",
    color: "#58a6ff",
    shape: [[0,0],[1,0],[0,1],[1,1],[0,2]],
    rarity: "rare",
    cost: 7,
    tags: ["armor"],
    defense: 4,
    cooldown: 0,
    effects: [
      { type: "passiveDefense", value: 4, trigger: "passive" },
      { type: "statMult", stat: "damage", value: 0.08, trigger: "passive" },
      { type: "gainStack", stack: "block", value: 45, trigger: "battle_start" }
    ],
    synergies: [
      { id: "migrated_block_1", adjacency: "strong", neighborTags: ["shield"], target: "neighbor", apply: { type: "blockBonus", value: 1 }, desc: "+1 блока" }
    ],
    description: "В начале боя: +45 блока.",
    buildHints: "Билд: выживание · Ветка: Stone / Vampiric / Holy / Ice Armor",
    sockets: 2,
  },
  leather_boots: {
    id: "leather_boots",
    name: "Кожаные сапоги",
    icon: "👢",
    color: "#a371f7",
    shape: [[0,0],[0,1]],
    rarity: "epic",
    cost: 6,
    tags: ["shoes","armor","luck"],
    cooldown: 3,
    effects: [
      { type: "block", value: 5 },
      { type: "hpThreshold", threshold: 0.7, direction: "below", once: true, trigger: "passive", gainStack: {"stack":"luck","value":1}, gainBlock: 15 }
    ],
    description: "При HP <70%: +1 удача и +15 блока (раз).",
    buildHints: "Билд: крит / Luck",
    sockets: 1,
  },
  leather_pouch: {
    id: "leather_pouch",
    name: "Кожаный мешочек",
    icon: "👝",
    color: "#8b6914",
    shape: [[0,0],[0,1]],
    internalCols: 1,
    internalRows: 2,
    isContainer: true,
    shopContainer: true,
    immovable: false,
    rarity: "common",
    cost: 2,
    tags: ["bag"],
    stats: {},
    cooldown: 0,
    effects: [],
    synergies: [],
    _isContainerEntry: true,
  },
  lucky_charm: {
    id: "lucky_charm",
    name: "Талисман",
    icon: "🍀",
    color: "#3fb950",
    shape: [[0,0],[1,0],[0,1],[1,1]],
    rarity: "common",
    cost: 2,
    tags: ["utility","gem","luck","accessory"],
    cooldown: 0,
    staminaCost: 0,
    effects: [
      { type: "passiveLuck", value: 35, trigger: "passive" }
    ],
  },
  lump_of_coal: {
    id: "lump_of_coal",
    name: "Кусок угля",
    icon: "🪨",
    color: "#8b949e",
    shape: shapeRect(2, 1),
    rarity: "common",
    cost: 2,
    tags: ["accessory","fire"],
    cooldown: 3,
    effects: [
      { type: "statMult", stat: "damage", value: 0.08, trigger: "passive" },
      { type: "groundFire", value: 1, trigger: "passive" },
      { type: "onHitCapBonus", value: 1, cap: 99, chance: 0.7, trigger: "on_hit" },
      { type: "gainStack", stack: "heat", value: 8, trigger: "battle_start" },
      { type: "periodic", interval: 3, trigger: "passive", gainWeakestStack: true }
    ],
    description: "70% +1 урона при атаке. В начале боя: +8 жара. Каждые 3с: случайный стак.",
    buildHints: "Билд: огонь / Pyromancer · Пары: Draconic Orb, Oil Lamp, Flame-крафты",
  },
  mana_crystal: {
    id: "mana_crystal",
    name: "Мана-кристалл",
    icon: "💎",
    color: "#a371f7",
    shape: [[0,0],[0,1]],
    rarity: "uncommon",
    cost: 5,
    tags: ["magic","gem"],
    damage: 4,
    cooldown: 2,
    staminaCost: 0,
    effects: [
      { type: "damage", value: 4, damageType: "magic", valueMin: 1, valueMax: 4 }
    ],
  },
  pan: {
    id: "pan",
    name: "Сковородка",
    icon: "🍳",
    color: "#8b949e",
    shape: [[0,0],[0,1]],
    rarity: "common",
    cost: 4,
    tags: ["weapon","melee","food","craft"],
    damage: 5,
    cooldown: 2,
    staminaCost: 2,
    effects: [
      { type: "damage", value: 5, valueMin: 5, valueMax: 6 },
      { type: "damagePerTag", tag: "food", value: 1, trigger: "passive" }
    ],
    synergies: [
      { id: "migrated_damage_1_per_tag", adjacency: "strong", neighborTags: ["food"], target: "self", apply: { type: "damageBonus", value: 1 }, desc: "+1 урона соседям" }
    ],
    description: "+1 урона за каждый предмет с тегом «еда».",
    buildHints: "Билд: еда / Pan · Ветка: Eggscalibur, Pandamonium, Shovel · Пары: любая еда (⭐)",
    sockets: 1,
  },
  pestilence_flask: {
    id: "pestilence_flask",
    name: "Ядовитое зелье",
    icon: "🧪☠️",
    color: "#a371f7",
    shape: [[0,0]],
    rarity: "epic",
    cost: 7,
    tags: ["potion","poison","consumable","craft"],
    cooldown: 3,
    effects: [
      { type: "poison", value: 3 },
      { type: "onFoeHeal", trigger: "passive", foePoison: 3, selfPoison: 1 }
    ],
    description: "Когда противник лечится: +3 яда ему и +1 себе.",
    buildHints: "Билд: яд · Крафт: Poison Dagger / Spear · Пары: Death Scythe, яд-питомцы",
  },
  piggybank: {
    id: "piggybank",
    name: "Копилка",
    icon: "🐷",
    color: "#8b949e",
    shape: [[0,0]],
    rarity: "common",
    cost: 3,
    tags: ["accessory","melee","treasure"],
    cooldown: 0,
    effects: [
      { type: "passiveMaxHp", value: 2, trigger: "passive" },
      { phase: "battle_start", type: "max_hp_per_start_item", value: 2, trigger: "passive" },
      { type: "max_hp_per_start_item", value: 2, trigger: "battle_start" }
    ],
    metaEffects: [
      { phase: "shop_enter", type: "gain_buff", value: 1 }
    ],
    description: "В начале боя: +2 макс. HP за каждый предмет «начало боя».",
    buildHints: "Билд: экономика / золото",
  },
  pineapple: {
    id: "pineapple",
    name: "Ананас",
    icon: "🍍",
    color: "#f0c14b",
    shape: [[0,0]],
    rarity: "legendary",
    cost: 6,
    tags: ["food","nature"],
    cooldown: 2.9,
    effects: [
      { type: "periodic", interval: 2.9, trigger: "passive", gainStack: {"stack":"luck","value":1}, heal: 4 },
      { type: "cooldownMultPerTag", tags: ["food"], perTag: 0.1, trigger: "passive" }
    ],
    description: "Каждые 2.9с: +1 удача и +4 HP. Быстрее за еду.",
    buildHints: "Билд: еда / Pan · Синергия: стан → Dagger extra attack",
  },
  pocket_sand: {
    id: "pocket_sand",
    name: "Карманный песок",
    icon: "🏖️",
    color: "#8b949e",
    shape: [[0,0]],
    rarity: "common",
    cost: 2,
    tags: ["accessory","debuff","nature"],
    cooldown: 0,
    effects: [
      { type: "statMult", stat: "damage", value: 0.08, trigger: "passive" },
      { type: "gainStack", stack: "luck", value: 1, trigger: "battle_start" }
    ],
    description: "В начале боя: +1 удача.",
    buildHints: "Универсальный / автономный",
  },
  poison_dagger: {
    id: "poison_dagger",
    name: "Ядовитый кинжал",
    icon: "🗡️",
    color: "#3fb950",
    shape: [[0,0],[0,1]],
    rarity: "common",
    cost: 3,
    tags: ["weapon","poison","melee"],
    damage: 2,
    cooldown: 2.6,
    staminaCost: 12,
    effects: [
      { type: "damage", value: 2, valueMin: 1, valueMax: 2 },
      { type: "poison", value: 2, trigger: "on_hit" },
      { type: "extraAttackOnStun", trigger: "passive" }
    ],
  },
  poison_vial: {
    id: "poison_vial",
    name: "Яд",
    icon: "☠️",
    color: "#3fb950",
    shape: [[0,0]],
    rarity: "common",
    cost: 2,
    tags: ["poison","consumable"],
    cooldown: 4.5,
    staminaCost: 0,
    effects: [
      { type: "poison", value: 1 }
    ],
  },
  protective_purse: {
    id: "protective_purse",
    name: "Защитная сумочка",
    icon: "👛🛡️",
    color: "#ff7b72",
    shape: [[0,0]],
    internalCols: 1,
    internalRows: 1,
    isContainer: true,
    shopContainer: true,
    immovable: false,
    rarity: "godly",
    cost: 2,
    tags: ["bag","shield","armor"],
    stats: {},
    cooldown: 0,
    effects: [],
    synergies: [],
    description: "+1 слот рюкзака. В начале боя: +15 блока.",
    buildHints: "Универсальный / автономный",
    _isContainerEntry: true,
  },
  rage_potion: {
    id: "rage_potion",
    name: "Зелье ярости",
    icon: "🧪",
    color: "#f85149",
    shape: [[0,0]],
    rarity: "uncommon",
    cost: 8,
    tags: ["food","potion"],
    cooldown: 6,
    staminaCost: 0,
    effects: [
      { type: "buffTimed", stat: "damage", value: 0.3, duration: 5 }
    ],
  },
  ripsaw_blade: {
    id: "ripsaw_blade",
    name: "Пила-раздиратор",
    icon: "🪚🩸",
    color: "#f0c14b",
    shape: [[0,0],[0,1]],
    rarity: "legendary",
    cost: 7,
    tags: ["weapon","spikes","melee"],
    damage: 9,
    cooldown: 1.7,
    staminaCost: 1.5,
    effects: [
      { type: "damage", value: 9, valueMin: 8, valueMax: 10 },
      { type: "stealWeaponDamage", value: 1, trigger: "on_hit" }
    ],
    description: "При попадании: украсть 1 урона с оружия противника.",
    buildHints: "Билд: шипы / отражение · Пары: Whetstone, Gloves of Haste",
    sockets: 3,
  },
  royal_helmet: {
    id: "royal_helmet",
    name: "Королевский шлем",
    icon: "👑",
    color: "#f0c14b",
    shape: [[0,0],[0,1]],
    classRestriction: "warrior",
    rarity: "legendary",
    cost: 10,
    tags: ["armor","helmet"],
    defense: 10,
    maxHp: 15,
    cooldown: 2.5,
    staminaCost: 0,
    effects: [
      { type: "passiveDefense", value: 10, trigger: "passive" },
      { type: "passiveMaxHp", value: 15, trigger: "passive" },
      { type: "block", value: 10 }
    ],
    synergies: [
      { id: "royal_block_buff", adjacency: "strong", neighborTags: ["weapon"], target: "self", apply: { type: "grantBlockBuff", value: 4, buffTargetTags: ["weapon"], cap: 20 }, desc: "[при блоке]: +4 к атаке соседнего оружия (макс. +20 за бой)" }
    ],
  },
  rusty_sword: {
    id: "rusty_sword",
    name: "Ржавый меч",
    icon: "🗡️",
    color: "#8b949e",
    shape: [[0,0],[0,1]],
    rarity: "common",
    cost: 2,
    tags: ["weapon","melee"],
    damage: 2,
    cooldown: 2.5,
    staminaCost: 12,
    effects: [
      { type: "damage", value: 2, valueMin: 1, valueMax: 3 }
    ],
  },
  shelly: {
    id: "shelly",
    name: "Шелли",
    icon: "🐚",
    color: "#58a6ff",
    shape: [[0,0]],
    rarity: "rare",
    cost: 6,
    tags: ["pet","holy"],
    cooldown: 13,
    effects: [
      { type: "periodic", interval: 13, trigger: "passive", cleanseDebuffs: 6, heal: 40 },
      { type: "procChanceBonus", value: 0.25, trigger: "passive" },
      { type: "cooldownMultPerTag", tags: ["potion"], perTag: 0.2, trigger: "passive" }
    ],
    description: "Каждые 13с: снять 6 дебаффов и +40 HP. +25% к снятию дебаффов.",
    buildHints: "Билд: питомцы",
  },
  shiny_shell: {
    id: "shiny_shell",
    name: "Блестящая раковина",
    icon: "🐚",
    color: "#8b949e",
    shape: [[0,0]],
    rarity: "common",
    cost: 2,
    tags: ["accessory","holy","nature"],
    cooldown: 5,
    effects: [
      { type: "healPerTag", tag: "holy", value: 3, trigger: "passive", adjacent: true },
      { type: "periodic", interval: 5, trigger: "passive", heal: 5 }
    ],
    description: "Каждые 5с: +5 HP и +3 за соседний святой предмет.",
    buildHints: "Билд: святой / Ranger · Крафт: Shelly, Shell Totem · Пары: Holy Armor, Divine Potion",
  },
  smoke_bomb: {
    id: "smoke_bomb",
    name: "Дымовая бомба",
    icon: "💨",
    color: "#8b949e",
    shape: [[0,0],[0,1]],
    classRestriction: "rogue",
    rarity: "legendary",
    cost: 10,
    tags: ["poison","utility","debuff"],
    cooldown: 4.5,
    staminaCost: 0,
    effects: [
      { type: "dodgePeriodic", interval: 3, trigger: "passive" },
      { type: "poison", value: 2 }
    ],
  },
  snow_stick: {
    id: "snow_stick",
    name: "Снежная палка",
    icon: "🪄❄️",
    color: "#f0c14b",
    shape: [[0,0],[0,1]],
    rarity: "legendary",
    cost: 8,
    tags: ["weapon","cold","melee"],
    damage: 7,
    cooldown: 1.8,
    staminaCost: 1,
    effects: [
      { type: "damage", value: 7, valueMin: 6, valueMax: 9 },
      { type: "poison", value: 3, trigger: "on_hit" },
      { type: "selfPoison", value: 2, trigger: "on_hit" }
    ],
    description: "При попадании: +3 яда противнику и +2 себе.",
    buildHints: "Билд: лёд · Пары: Whetstone, Gloves of Haste",
    sockets: 1,
  },
  snowball: {
    id: "snowball",
    name: "Снежок",
    icon: "⛄",
    color: "#a371f7",
    shape: [[0,0]],
    rarity: "epic",
    cost: 4,
    tags: ["accessory","cold","craft"],
    cooldown: 0,
    effects: [
      { type: "statMult", stat: "damage", value: 0.08, trigger: "passive" },
      { type: "gainStack", stack: "cold", value: 2, targetSide: "foe", trigger: "battle_start" }
    ],
    description: "В начале боя: наложить 2 холода на противника.",
    buildHints: "Билд: лёд",
  },
  snowcake: {
    id: "snowcake",
    name: "Снежный пирог",
    icon: "🍰❄️",
    color: "#ffa657",
    shape: [[0,0]],
    rarity: "unique",
    cost: 6,
    tags: ["food","cold"],
    cooldown: 4,
    effects: [
      { type: "slow", value: 0.12, duration: 4 },
      { type: "periodic", interval: 3, trigger: "passive", gainStack: {"stack":"cold","value":1,"targetSide":"foe"}, foeColdBonus: {"threshold":10,"magicDamageMult":0.1,"damage":10,"damageType":"magic"} },
      { type: "cooldownMultPerTag", tags: ["food"], perTag: 0.1, trigger: "passive" }
    ],
    description: "Каждые 3с: +1 холод. При 10+ холода у противника: +10% маг. урона и 10 маг. урона.",
    buildHints: "Билд: лёд, еда / Pan",
  },
  spark_stone: {
    id: "spark_stone",
    name: "Искорка",
    icon: "✨",
    color: "#d2a8ff",
    shape: [[0,0]],
    rarity: "uncommon",
    cost: 4,
    tags: ["utility","magic"],
    cooldown: 3,
    staminaCost: 0,
    effects: [
      { type: "damage", value: 3, damageType: "magic", valueMin: 1, valueMax: 3 }
    ],
  },
  spear: {
    id: "spear",
    name: "Копьё",
    icon: "🔱",
    color: "#58a6ff",
    shape: [[0,0],[0,1],[0,2]],
    rarity: "rare",
    cost: 6,
    tags: ["weapon","melee","craft"],
    damage: 5,
    cooldown: 1.5,
    staminaCost: 1,
    effects: [
      { type: "damage", value: 5, valueMin: 3, valueMax: 8 },
      { type: "breakBlockOnHit", value: 4, trigger: "on_hit" }
    ],
    description: "При попадании: снять 4 блока у противника.",
    buildHints: "Билд: анти-блок · Оставлять пустые клетки впереди · Ветка: Poison / Holy / Molten Spear",
    sockets: 1,
  },
  star_of_courage: {
    id: "star_of_courage",
    name: "Звезда мужества",
    icon: "⭐",
    color: "#58a6ff",
    shape: [[0,0]],
    rarity: "rare",
    cost: 1,
    tags: ["accessory","holy"],
    cooldown: 0,
    effects: [],
    synergies: [
      { id: "star_courage_aura", adjacency: "strong", neighborTags: ["weapon","pet","armor","shield"], target: "neighbor", apply: { type: "damageBonus", value: 2 }, desc: "+2 урона соседним предметам" }
    ],
    metaEffects: [
      { phase: "passive", type: "starting_value", value: 1 }
    ],
    description: "Стартовый предмет из случайного броска сумки. Стоимость 1 золота; нет боевого эффекта.",
    buildHints: "Универсальный / автономный",
  },
  stone: {
    id: "stone",
    name: "Камень",
    icon: "🪨",
    color: "#8b949e",
    shape: [[0,0]],
    rarity: "common",
    cost: 1,
    tags: ["accessory","nature"],
    damage: 3,
    cooldown: 4,
    staminaCost: 0,
    effects: [
      { type: "damage", value: 3, valueMin: 2, valueMax: 4 },
      { type: "activationLimit", base: 1, trigger: "passive" },
      { type: "destroyFoeStacks", value: 4, trigger: "on_hit" }
    ],
    description: "1 бросок за бой. При попадании: уничтожить 4 стака противника.",
    buildHints: "Универсальный / автономный",
  },
  stone_skin_potion: {
    id: "stone_skin_potion",
    name: "Зелье каменной кожи",
    icon: "🧪🪨",
    color: "#a371f7",
    shape: [[0,0]],
    rarity: "epic",
    cost: 6,
    tags: ["potion","consumable"],
    cooldown: 3,
    effects: [
      { type: "buffTimed", stat: "damage", value: 0.1, duration: 6 },
      { type: "stackThreshold", stack: "block", threshold: 45, once: true, trigger: "passive", convertHp: {"hpCost":15,"stack":"regen","stackGain":30} }
    ],
    description: "При 45 блока: −15 HP → +30 регена (раз).",
    buildHints: "Универсальный / автономный",
  },
  storm_burst: {
    id: "storm_burst",
    name: "Удар бури",
    icon: "🌩️",
    color: "#58a6ff",
    shape: [[0,0],[0,1]],
    rarity: "rare",
    cost: 5,
    tags: ["weapon","magic"],
    cooldown: 5.5,
    staminaCost: 2,
    effects: [
      { type: "spendStack", stack: "mana", value: 1, attackBuff: 8 },
      { type: "damage", value: 4, damageType: "magic", valueMin: 1, valueMax: 4 }
    ],
    description: "[при активации]: потратить 1 ману → +8 урона и магический удар.",
  },
  thorn_whip: {
    id: "thorn_whip",
    name: "Шипастый кнут",
    icon: "🪢🌵",
    color: "#a371f7",
    shape: [[0,0],[0,1]],
    rarity: "epic",
    cost: 8,
    tags: ["weapon","melee","spikes","craft"],
    damage: 6,
    cooldown: 2.3,
    staminaCost: 2.5,
    effects: [
      { type: "damage", value: 6, valueMin: 4, valueMax: 9 },
      { type: "gainStack", stack: "spikes", value: 1, trigger: "on_hit" },
      { type: "damagePerStack", stack: "spikes", value: 1, trigger: "passive" }
    ],
    description: "При попадании: +1 шип. +1 урона за каждый шип.",
    buildHints: "Билд: шипы · Крафт: Bloodthorne, Flame Whip · Пары: Walrus Tusk",
    sockets: 2,
  },
  titan_armor: {
    id: "titan_armor",
    name: "Доспех титана",
    icon: "🦾",
    color: "#a371f7",
    shape: [[0,0],[1,0],[0,1],[1,1]],
    rarity: "rare",
    cost: 10,
    tags: ["armor"],
    defense: 16,
    maxHp: 15,
    cooldown: 0,
    staminaCost: 0,
    effects: [
      { type: "passiveDefense", value: 16, trigger: "passive" },
      { type: "passiveMaxHp", value: 15, trigger: "passive" }
    ],
  },
  vampiric_potion: {
    id: "vampiric_potion",
    name: "Вампирское зелье",
    icon: "🧪🩸",
    color: "#f0c14b",
    shape: [[0,0]],
    rarity: "legendary",
    cost: 8,
    tags: ["potion","consumable","vampiric"],
    cooldown: 3,
    effects: [
      { type: "buffTimed", stat: "damage", value: 0.1, duration: 6 },
      { type: "lifesteal", value: 0.05, trigger: "passive" },
      { type: "mutualHpThreshold", threshold: 0.8, once: true, trigger: "passive", gainStack: {"stack":"mana","value":3}, damage: 15, damageType: "magic", lifesteal: 1 },
      { type: "mutualHpThreshold", threshold: 0.8, once: true, trigger: "passive", gainStack: {"stack":"mana","value":3}, damage: 15, damageType: "magic", lifesteal: 1 },
      { type: "mutualHpThreshold", threshold: 0.8, once: true, trigger: "passive", gainStack: {"stack":"mana","value":3}, damage: 15, damageType: "magic", lifesteal: 1 }
    ],
    description: "Оба ниже 80% HP: +3 маны, 15 маг. урона с 100% вампиризмом.",
    buildHints: "Билд: вампиризм · Пары: Blood Amulet, Hungry Blade, Blood Goobert",
  },
  villain_sword: {
    id: "villain_sword",
    name: "Меч злодея",
    icon: "🗡️😈",
    color: "#ffa657",
    shape: [[0,0],[0,1]],
    rarity: "unique",
    cost: 7,
    tags: ["weapon","melee","dark"],
    damage: 3,
    cooldown: 1.2,
    staminaCost: 0.7,
    effects: [
      { type: "damage", value: 3, valueMin: 2, valueMax: 4 },
      { type: "damagePerTag", tag: "dark", value: 4, trigger: "passive" }
    ],
    synergies: [
      { id: "migrated_damage_4_per_melee", adjacency: "strong", neighborTags: ["weapon"], target: "neighbor", apply: { type: "damageBonus", value: 4 }, desc: "+4 урона соседям" }
    ],
    description: "+4 урона за каждый тёмный предмет.",
    buildHints: "Билд: тёмный carry · Пары: много соседних мечей (⭐)",
    sockets: 1,
  },
  wooden_buckler: {
    id: "wooden_buckler",
    name: "Деревянный щиток",
    icon: "🛡️🪵",
    color: "#8b949e",
    shape: [[0,0],[1,0]],
    rarity: "common",
    cost: 4,
    tags: ["shield","armor"],
    cooldown: 3,
    effects: [
      { type: "block", value: 5 },
      { type: "onDefend", chance: 0.3, trigger: "passive", preventDamage: 7, drainStamina: 0.3 }
    ],
    description: "При блоке/уклонении (30%): −7 урона, −0.3 выносливости противнику.",
    buildHints: "Универсальный / автономный",
    sockets: 1,
  },
  wooden_sword: {
    id: "wooden_sword",
    name: "Деревянный меч",
    icon: "🗡️🪵",
    color: "#8b949e",
    shape: [[0,0],[0,1]],
    classRestriction: "rogue",
    rarity: "common",
    cost: 3,
    tags: ["weapon","melee","craft"],
    damage: 2,
    cooldown: 1.4,
    staminaCost: 1,
    effects: [
      { type: "damage", value: 2, valueMin: 1, valueMax: 3 },
      { type: "onHitCapBonus", value: 1, cap: 2, chance: 0.25, trigger: "on_hit" }
    ],
    description: "25% +1 урона (до 2).",
    buildHints: "Старт Ranger · Крафт: → Hero Sword · Пары: Whetstone для раннего апгрейда",
    sockets: 1,
  },
  starter_bag: {
    id: "starter_bag",
    name: "Сумка",
    icon: "👜",
    color: "#6e4c2a",
    shape: [[0,0],[1,0],[2,0],[0,1],[1,1],[2,1],[0,2],[1,2],[2,2]],
    internalCols: 3,
    internalRows: 3,
    isContainer: true,
    immovable: true,
    rarity: "common",
    cost: 0,
    tags: ["bag"],
    stats: {},
    cooldown: 0,
    effects: [],
    synergies: [],
    _isContainerEntry: true,
  }
};

const CRAFT_OUTPUT_IDS = new Set([]);

function buildItemCatalog() {
  const out = {};
  Object.entries(ITEM_CATALOG_RAW).forEach(([key, opts]) => {
    if (opts._isContainerEntry) {
      const { _isContainerEntry, ...container } = opts;
      out[key] = container;
      return;
    }
    out[key] = defItem(opts);
  });
  return out;
}

const ITEM_CATALOG = buildItemCatalog();

if (typeof resolveItemSlot === "function") {
  Object.values(ITEM_CATALOG).forEach((item) => {
    item.slot = resolveItemSlot(item);
  });
}
